# Change these first
owner: evantahler # Your GitHub username
repo: upptime # Your Github repository name

# Add your sites here
sites:
  - name: www.evantahler.com
    url: https://www.evantahler.com
    icon: https://github.com/evantahler/www.evantahler.com/blob/master/public/static/images/evan.jpg

assignees: # Users to assign downtime issues (optional)
  - evantahler

status-website:
  cname: status.evantahler.com
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** Monitoring Evan's Sties"
  introMessage: This is a sample status page which uses **real-time** data from our [Github repository](https://github.com/evantahler/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
